%datos(id,nombre,genero,año,psinopsis,duracion,actores, idioma,cosoto,enlaces para adquirir la película)
%drama
pelicula(1,'Cadena Perpetua',drama,1995,'En 1947, Andy Dufresne (Tim Robbins), un joven banquero, es condenado a cadena perpetua por asesinar a su esposa y su amante.',142,'Tim Robbins, Morgan Freeman, Bob Gunton', 'Inglés',135, 'https://www.youtube.com/watch?v=eTRvl89d5uM',no).
pelicula(2,'Forrest Gump',drama,1994,'Al tener el coeficiente intelectual de un niño, Forrest Gump siempre ha sido considerado el “tonto” de clase.',95,'Tom Hanks, Gary Sinise, Robin Wright', 'Inglés', 120,'https://www.youtube.com/watch?v=MgqzfiiA70g',no).
pelicula(3,'12 Hombres sin piedad',drama,1957,'Multipremiado drama judicial de Sidney Lumet en el que un brillante reparto se encarga de dar vida a un jurado popular en un caso de parricidio.',96,'Henry Fonda, Lee J. Cobb', 'Inglés', 100, 'https://www.youtube.com/watch?v=jO3kJ8w_1L8',no).
pelicula(4,'El Pianista',drama,2002,'Durante la Segunda Guerra Mundial, Wladyslaw Szpilman, un célebre pianista judío de origen polaco, escapa a la deportación, pero se encuentra hacinado en el gueto de Varsovia, donde comparte con los demás sufrimientos, humillaciones y luchas heroicas.',148,'Adrien Brody, Thomas Kretschmann, Emilia Fox', 'Inglés', 150,'https://www.youtube.com/watch?v=TAjDERf7ISk',no).
pelicula(5,'Intocable',drama,2012,'Philippe (François Cluzet, No se lo digas a nadie) es un hombre adinerado que pertenece a la alta sociedad.',112, 'François Cluzet, Omar Sy, Anne Le Ny','Francés', 155, 'https://www.youtube.com/watch?v=cXu2MhWYUuE',no).
pelicula(6,'En Busca de la Felicidad',drama,2007,'Chris Gardner, un joven padre de familia, está tratando de ganarse la vida.',118, 'Will Smith, Thandiwe Newton, Jaden Smith', 'Inglés', 120, 'https://www.youtube.com/watch?v=APMv2gOxbxM',no).
pelicula(7,'Hachiko',drama,2009,'Parker Wilson (Richard Gere, El caso Wells) es un profesor de universidad que trabaja lejos de su casa.',93, 'Richard Gere, Joan Allen, Sarah Roemer', 'Inglés', 130,'https://www.youtube.com/watch?v=Vux6KhlrERk',no).
pelicula(8,'Interstellar',drama,2020,'Inspirada en la teoría del experto en relatividad Kip Stepehen Thorne sobre la existencia de los agujeros de gusano, y su función como canal para llevar a cabo los viajes en el tiempo.',169, 'Matthew McConaughey, Anne Hathaway', 'Inglés', 120,'https://www.youtube.com/watch?v=3Ns4f0H19w0',no).
pelicula(9,'El niño con el Pijama de Rayas',drama,2008,'Bruno (Assa Butterfield) es un niño de 9 años que se ve obligado a abandonar Berlín y dejar atrás a sus amigos cuando su padre, un oficial nazi, recibe el mando del campo de concentración de Auschwitz.',90, 'Asa Butterfield', 'Inglés', 130,'https://www.youtube.com/watch?v=rzow19gyNqQ',no).
pelicula(10,'Criadas y Señoras',drama,2011,'Ambientada en el Mississippi de los años sesenta, narra la historia de Skeeter (Emma Stone, Rumores y mentiras), una joven sureña de Estados Unidos que vuelve de la universidad con el sueño de convertirse en escritora.',146, 'Emma Stone, Viola Davis', 'Inglés', 100, 'https://www.youtube.com/watch?v=HJFQr3MYMZc',no).

%accion
pelicula(11,'Rapidos y Furiosos X',accion,2023,'Décima y última entrega de la saga Fast & furious. Para su desenlace, Dom Toretto (Vin Diesel) vuelve a la carga con más carreras, velocidad y acción desenfrenada.',141,'Vin Diesel, Jason Momoa, Alan Richton', 'Inglés',200,'https://www.youtube.com/watch?v=qI17550IwW4',si).
pelicula(12,'Gladiador',accion,2000,'En el año 180 el Imperio Romano controla todo el mundo conocido hasta la fecha.',155,'Russell Crowe, Joaquin Phoenix, Connie Nielsen ', 'Inglés', 120,'https://www.youtube.com/watch?v=Sm5D1cLaKpY',no).
pelicula(13,'Predator: La presa',accion,2022,'La historia del filme narra el origen de Predator, uno de los mayores depredadores que la Tierra ha sufrido.',99,' Amber Midthunder, Dakota Beavers, Dane DiLiegro', 'Inglés',120,'https://www.youtube.com/watch?v=Wh1fEipFcCM',no).
pelicula(14,'Pearl Harbor',accion,2001,'La acción nos sitúa en la Segunda Guerra Mundial; Rafe (Ben Affleck, Diario de un ejecutivo agresivo) y Danny (Josh Hartnett, 40 días y 40 noches) son dos amigos que crecieron y vivieron juntos, además, se formaron a la vez como pilotos en la base de las fuerzas aéreas',210,'Ben Affleck, Josh Hartnett, Kate Beckinsale ', 'Inglés', 110,'https://www.youtube.com/watch?v=mS6Z-WLdr5Q',no).
pelicula(15,'John Wick (Un Buen Dia Para Matar)',accion,2022,'John Wick, interpretado por Keanu Reeves (Matrix, Pactar con el diablo) es un antiguo asesino a sueldo que observa impasible cómo un ladrón roba su coche, un Ford Mustang del 69, y mata al perro que su mujer le regaló.',101,' Keanu Reeves, Michael Nyqvist, Alfie Allen', 'Inglés',150,'https://www.youtube.com/watch?v=CKBFV1xltqg',no).
pelicula(16,'Kingsman',accion,2015,'Dentro del estilo característico de la adaptación de una historia gráfica, Kingsman: Servicio secreto cuenta la historia de un delincuente adolescente que se mueve por los barrios bajos de Londres y que pronto verá que su vida da un giro de 180 grados gracias a la ayuda de un misterioso hombre.',129,' Taron Egerton, Colin Firth, Samuel L. Jackson', 'Inglés',130,'https://www.youtube.com/watch?v=Rs5J8kh62yo',no).
pelicula(17,'Los Juegos del Hambre',accion,2012,'Los juegos del hambre, nos muestra un mundo distópico donde los Estados Unidos han sido devastados tras varias guerras, convirtiéndose en una nueva nación llamada Panem, un estado donde reina la pobreza.',142,'Jennifer Lawrence, Josh Hutcherson ', 'Inglés',120,'https://www.youtube.com/watch?v=qNtUMdZxaHM',no).
pelicula(18,'Troya',accion,2004,'Los príncipes de Troya, Héctor (Eric Bana) y Paris (Orlando Bloom), son invitados a una fiesta por el rey Menelao (Brendan Gleeson) y, una vez allí, Paris se enamora perdidamente de la esposa de este, Helena (Diane Kruger).',155,' Brad Pitt, Eric Bana, Orlando Bloom', 'Inglés',130,'https://www.youtube.com/watch?v=Zv1qpQ5OtAQ',no).
pelicula(19,'Matrix',accion,1999,'Neo (Keanu Reeves) es un joven pirata informático que lleva una doble vida: durante el día ejerce en una empresa de servicios informáticos, mientras que por la noche se dedica a piratear bases de datos y saltarse sistemas de alta seguridad.',135,' Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss', 'Inglés',120,'https://www.youtube.com/watch?v=CL-i6XsoNpg',no).
pelicula(20,'Triple X',accion,2002,'Tras una serie de pruebas, Xander "xXx" Cage, un especialista en deportes extremos y cubierto de tatuajes, es reclutado por Augustus Gibbons, un agente de la Agencia de Seguridad Nacional (NSA), para que se infiltre en una organización criminal y ponga fin a sus operaciones.',124,'Vin Diesel, Samuel L. Jackson, Asia Argento ', 'Inglés',110,'https://www.youtube.com/watch?v=3IZ2rM0SXuM',no).

%romance
pelicula(21,'Mujer Bonita',romance,1990,'Edward Lewis (Richard Gere) es un hombre de negocios solitario. Una noche contrata los servicios de Vivian Ward (Julia Roberts), una prostituta.',120,'Richard Gere, Julia Roberts, Ralph Bellamy','Español', 120,'https://www.youtube.com/watch?v=IOzoZ-tT5GM&ab_channel=Empeliculados.Co',no).
pelicula(22,'Antes de Ti',romance,2016,'Lou Clark (Emilia Clarke) es una entusiasta, ingenua y alegre veinteañera que jamás ha salido de su pueblo, y que debe buscar urgentemente un trabajo para mantener a su familia.',110,'Emilia Clarke, Sam Claflin, Janet McTeer','Español',110,'https://www.youtube.com/watch?v=IOzoZ-tT5GM&ab_channel=Empeliculados.Co',no).
pelicula(23,'Titanic',romance,1998,'Jack (Leonardo DiCaprio, El gran Gatsby), un humilde y joven artista, y Rose (Kate Winslet, Un Dios salvaje), una chica de clase acomodada, se conocerán a bordo del Titanic, el barco más espectacular que jamás haya surcado los siete mares',194,' Leonardo DiCaprio, Kate Winslet, Billy Zane','Español', 130,'https://www.youtube.com/watch?v=tA_qMdzvCvk&ab_channel=20thCenturyStudiosLA',no).
pelicula(24,'Crepusculo',romance,2008,'Isabella Swan, de 17 años, se muda a Forks, una pequeña ciudad lluviosa del estado de Washington, para vivir con su padre.',130, 'Kristen Stewart, Robert Pattinson, Taylor Lautner', 'Español',110,'https://www.youtube.com/watch?v=6UTwp0Qv_Sg&ab_channel=Cin%C3%A9polisArgentina',no).
pelicula(25,'A Dos Metros De Ti',romance,2019,'Stella tiene diecisiete años y a diferencia del resto de sus otros amigos vive una vida con una rutina bastante diferente.',120,'Haley Lu Richardson, Cole Sprouse, Moises Arias.','Español',130,'https://www.youtube.com/watch?v=9Lt8QAZkc94&ab_channel=20thCenturyStudiosEspa%C3%B1a',no).
pelicula(26,'Bajo La Misma Estrella',romance,2014,'Hazel y Gus son dos adolescentes cuyas vidas distan mucho de ser normales.',125,'Shailene Woodley, Ansel Elgort, Nat Wolff.','Español',180,'https://www.youtube.com/watch?v=5LC1f2kB0iY&ab_channel=YouTubeMovies',no).
pelicula(27,'Orgullo y Prejuicio', romance,2006,'Finales del siglo XVIII en Inglaterra. En una familia de cinco hijas, la madre les ha enseñado que el único propósito que tienen que tener en la vida es encontrar un marido.',1292,'Keira Knightley, Matthew Macfadyen, Rosamund Pike', 'Español',140,'https://www.youtube.com/watch?v=J6OKfv9Rl6s&ab_channel=YouTubeMovies',no).
pelicula(28,'Una Cuestion de Tiempo', romance,2013,'Tim Lake (Domhnall Gleeson, Anna Karenina) descubre a los 21 años que tiene, al igual que todos los hombres de su familia, la capacidad de viajar en el tiempo.',123,'Domhnall Gleeson, Bill Nighy, Rachel McAdams','Español',106,'https://www.youtube.com/watch?v=jposnP4GKyk&ab_channel=LaAventuraCine',no).
pelicula(29,'Los Improvistos Del Amor', romance,2023,'Los imprevistos del amor cuenta la historia de dos íntimos amigos, Rosie (Lily Collins, Cazadores de sombras: Ciudad de hueso, El sicario de Dios) y Alex (Sam Claflin, Blancanieves y la leyenda del cazador, Los juegos del hambre: En llamas).',102,'Lily Collins, Sam Claflin, Christian Cooke','Español',180,'https://www.youtube.com/watch?v=KyxQFrIdRAQ&ab_channel=TrailersInSpanish',si).
pelicula(30,'Perdona Si Te Llamo Amor',romance,2023,'El conocido best seller de Federico Moccia Perdona si te llamo amor, llega ahora a los cines de la mano de Joaquín LLamas (Tierra de lobos, La Baronesa). ',120, 'Daniele Liotti, Paloma Bloyd, Irene Montala', 'Español',170,'https://www.youtube.com/results?search_query=perdona+si+te+llamo+amor+pelicula+en+espa%C3%B1ol',si).

%suspenso
pelicula(31,'Marlowe',suspenso, 2023,'Los malos negocios y la soledad hacen mella en la vida del detective privado Philip Marlowe (Liam Neeson).' ,110, 'Liam Neeson, Diane Kruger, Jessica Lange','Español',140,'https://www.youtube.com/watch?v=MRFGH11geTo&ab_channel=YouTubeMovies',si).
pelicula(32,'Megalodon',suspenso, 2018,'En el lugar más profundo del planeta, todavía más hondo que la propia fosa de las Marianas, un grupo de investigadores se encuentra realizando una expedición como parte de un programa internacional de vigilancia submarina.', 114,'Jason Statham, Bin, gbing Li, Rainn Wilson','Español',120,'https://www.youtube.com/watch?v=K4oYDfGF414&ab_channel=YouTubeMovies',no).
pelicula(33,'La Cara Oculta',suspenso, 2011,'En realidad Belén no se ha ido demasiado lejos. Al comprar la casa le mostraron una habitación oculta a modo de búnker en la que protegerse en caso de robo.', 96,'Quim Gutiérrez, Martina García, Clara Lago','Español',150,'https://www.youtube.com/watch?v=Ts1PhDpWyCw&ab_channel=DYNAMO',no).
pelicula(34,'El Perfume',suspenso,2006,'Francia, mediados del siglo XVIII. Jean Baptiste Grenouille es un joven que ha tenido una vida muy dura.',147, 'Ben Whishaw, Dustin Hoffman, Alan Rickman','Español',120,'https://www.youtube.com/watch?v=9WU_s8q2eQo&ab_channel=Filmax',no).
pelicula(35,'Un Ciudadano Ejemplar',suspenso,2010,'Clyde Shelton lo ha perdido todo. Hace diez años que su mujer y su hija fueron asesinadas, y el culpable está en libertad.',109,'Gerard Butler, Jamie Foxx, Leslie Bibb', 'Español',160,'https://www.youtube.com/watch?v=hL9A1iqu5ck&ab_channel=ElGatoCheshire',no).
pelicula(36,'It',suspenso,2017,'Son los años 80 en el pequeño pueblo de Derry, en el estado de Maine. En él vive una panda de siete niños conocidos como El club de los perdedores, que debe enfrentarse a sus problemas cotidianos con los matones de la escuela.',105,'Bill Skarsgård, Jaeden Martell, Finn Wolfhard','Español',180,'https://www.youtube.com/watch?v=CwSJL3Cky_4&ab_channel=YouTubeMovies',no).
pelicula(37,'Origen',suspenso,2010,'Dom Cobb (Leonardo DiCaprio) es el mejor extractor. Su oficio consiste en introducirse en los sueños de sus víctimas y extraerle secretos del mundo de los negocios para luego venderlos con grandes dividendos.',148,'Leonardo DiCaprio, Marion Cotillard, Elliot Page', 'Español', 140, 'https://www.youtube.com/watch?v=RV9L7ui9Cn8&ab_channel=WarnerBrosInception',no).
pelicula(38,'No respires 2',suspenso, 2021,'En esta secuela del filme de terror No respires (2016), el ex militar ciego que causó estragos en la primera entrega, volverá a verse envuelto en problemas.',99,'Stephen Lang, Madelyn Grace, Brendan Sexton III','Español', 140,'https://www.youtube.com/watch?v=f94_p2RpjfU&ab_channel=YouTubeMovies',no).
pelicula(39,'La Piel Que Habito',suspenso, 2011,'Robert Ledgard (Antonio Baneras) es un eminente cirujano plástico que realiza sus experimentos en su clínica privada, El Cigarral.',117,'Antonio Banderas, Elena Anaya, Marisa Paredes', 'Español', 175,'https://www.youtube.com/watch?v=qxbfv6t6z3I&ab_channel=CineXcusas',no).
pelicula(40,'Nop!',suspenso, 2022, 'Este thriller sigue a los trabajadores del rancho de Hayward, un lugar de doma de caballos de Hollywood. En medio de un árido paraje, nada ni nadie irrumpe en su tranquila rutina.' ,130,'Daniel Kaluuya, Keke Palmer, Steven Yeun','Español',190,'https://www.youtube.com/watch?v=v-hlPfBJt6k&ab_channel=TrailersInSpanish',no).

%fantasia
pelicula(41,'La Sirenita', fantasia, 2023,'Ariel es una joven y soñadora sirena, hija del Rey Tritón, que está cansada de su vida como princesa bajo el mar.',136,'Noma Dumezweni, Art Malik, Halle Bailey', 'Español', 125, 'https://www.youtube.com/watch?v=8LECfkm4fJA&ab_channel=SensaCineTRAILERS',si).
pelicula(42,'Los Caballeros Del Zodiaco', fantasia, 2023,'Película de acción real basada en la saga anime Los caballeros del Zodiaco. ',102,'Mackenyu, Famke Janssen, Sean Bean', 'Español',145,'https://www.youtube.com/watch?v=CLiniBPN_R4&ab_channel=SensaCineTRAILERS',si).
pelicula(43,'Mavka, Guardiana Del Bosque', fantasia,2023,'Mavka es una de las hadas guardianas de El Bosque que protege la naturaleza.',99,'Elena Kravets', 'Español',145,'https://www.youtube.com/watch?v=GXaMT5pX12w&ab_channel=FILM.UAGroup',si).
pelicula(44,'Avatar', fantasia, 2022,'Varios años después de los sucesos ocurridos en Avatar (2009), volvemos a Pandora donde Jake Sully (Sam Worthington) y Neytiri (Zoe Saldana) han formado una familia.',192,'Sam Worthington, Zoe Saldana, Sigourney Weaver','Español',185,'https://www.youtube.com/watch?v=CpXJHWSXJW0&ab_channel=CineFantasia',no).
pelicula(45,'Alicia en el Pais de la Maravillas', fantasia, 2010,'Tras diez años, Alicia vuelve al País de las Maravillas, del que parece no recordar nada.',108,'Johnny Depp, Mia Wasikowska, Michael Sheen', 'Español',155,'https://www.youtube.com/watch?v=Gyu7zvy8leg&ab_channel=DisneyEspa%C3%B1a',no).
pelicula(46,'Constanntine', fantasia, 2005,'El irreverente detective de casos sobrenaturales John Constantine (Keanu Reeves) cuenta con un don especial: es capaz de ver los espíritus que vagan por la Tierra con aspecto de seres humanos.',120,'Keanu Reeves, Rachel Weisz, Djimon Hounsou','Español',140,'https://www.youtube.com/watch?v=M8APRgAXguc&ab_channel=TERRORLAND',no).
pelicula(47,'Un Monstruo Viene a Verme', fantasia,2016,'Conor O Malley (Lewis MacDougall) es un chico que a sus 13 años ha tenido que asumir muchas responsabilidades.',108, 'Lewis MacDougall, Felicity Jones, Sigourney Weaver','Español',145,'https://www.youtube.com/watch?v=pxDiw5IDDFg&ab_channel=YouTubeMovies',no).
pelicula(48,'La Bella y La Bestia',fantasia,2017,'Una joven soñadora y romántica llamada Bella (Emma Watson) vive en una pequeña aldea junto a su padre, un inventor de artilugios, al que algunos consideran un anciano demente.',129,'Emma Watson, Dan Stevens, Luke Evans','Español',180,'https://www.youtube.com/watch?v=XpMjfUJ1lUc&ab_channel=DisneyEspa%C3%B1a',no).
pelicula(49,'Las Cronica De Narnia', fantasia,2005,'Las crónicas de Narnia cuenta la lucha entre el bien y el mal que opone al magnífico león Aslan contras las fuerzas tenebrosas del mundo mágico de Narnia.',140,' Georgie Henley, Skandar Keynes, Anna Popplewell','Español',165,'https://www.youtube.com/watch?v=PKEimNXpuQo&ab_channel=Tr%C3%A1ilersconDoblajeEspa%C3%B1olLatinobySoldierBoy',no).
pelicula(50,'El Laberinto del Fauno', fantasia, 2006,'Han pasado cinco años desde el fin de la Guerra Civil en España y el ambiente sigue cargado de temor y odio.',117,'Ivana Baquero, Sergi López, Doug Jones','Español',125,'https://www.youtube.com/watch?v=gpEh4O8Hb5Y&ab_channel=Recomiendo%23Cine',no).

%comedia
pelicula(51,'Scary Movie', comedia, 2000, 'Una noche, Drew Becker recibe una llamada anónima de un maníaco.' ,84,' Anna Faris, Shawn Wayans, Marlon Wayans','Español',135,'https://www.youtube.com/watch?v=B1jRfdSTf3Q&ab_channel=YouTubeMovies',no).
pelicula(52,'American Pie', comedia, 1999,'Mortificado por haber sido descubierto por sus padres viendo una película X, Jim, alumno del último año de instituto, hace un pacto con sus amigos: convertirse en hombres antes de entrar en la universidad.',95,'Jason Biggs, Seann William Scott, Chris Klein','Español',135,'https://www.youtube.com/watch?v=wvTGun7Htn8&ab_channel=YouTubeMovies',no).
pelicula(53,'Vacaciones', comedia,2015,'Con el fin de volver a juntar a su desequilibrada familia y fortalecer los lazos familiares, Rusty Griswold (Ed Helms) decide repetir el viaje de vacaciones familiares que hizo cuando era pequeño',99,'Ed Helms, Christina Applegate, Skyler Gisondo','Español',195,'https://www.youtube.com/watch?v=KS3i1Kt_y7Q&ab_channel=WarnerBros.PicturesEspa%C3%B1a',no).
pelicula(54,'Free Guy', comedia,2021,'Guy es un tipo alegre que trabaja como cajero de un banco.',105,'Ryan Reynolds, Jodie Comer, Lil Rel Howery','Español',120,'https://www.youtube.com/watch?v=tZbNDmRGx_M&ab_channel=TrailersInSpanish',no).
pelicula(55,'Un Golpe Con Estilo', comedia,2017,'Willie (Morgan Freeman), Joe (Michael Caine) y Al (Alan Arkin) son tres amigos jubilados a los que el sistema les ha congelado su plan de pensiones.' ,96,'Morgan Freeman, Michael Caine, Alan Arkin','Español',120,'https://www.youtube.com/watch?v=K6tK6d2Hqws&ab_channel=WarnerBros.PicturesEspa%C3%B1a',no).
pelicula(56,'Matilda', comedia, 1996,'La película cuenta la historia de Matilda Wormwood (Mara Wilson), una niña superdotada cuya inteligencia supera con creces a la de su inculta familia.',98,'Mara Wilson, Danny DeVito, Rhea Perlman','Español',145,'https://www.youtube.com/watch?v=dAwR3Oq3AgI&ab_channel=YouTubeMovies',no).
pelicula(57,'Deadpool', comedia, 2016, 'Después de alistarse en el ejército, Wade Wilson (Ryan Reynolds) comienza a realizar trabajos de mercenario, y acabará siendo agente de las Fuerzas Especiales de EE.UU. ',108,'Ryan Reynolds, Morena Baccarin, Ed Skrein','Español',195,'https://www.youtube.com/watch?v=0JnRdfiUMa8&ab_channel=20thCenturyStudiosLA',no).
pelicula(58,'Renfield', comedia, 2023, 'En esta comedia de terror Nicholas Hoult da vida a Renfield, el atormentado ayudante de Drácula (interpretado por Nicolas Cage).' ,93,'Nicholas Hoult, Nicolas Cage, Awkwafina','Español',120,'https://www.youtube.com/watch?v=J093zSvG-LI&ab_channel=TrailersInSpanish',si).
pelicula(59,'Los Simpson:La Pelicula', comedia, 2007,'Green Day es el grupo encargado de tararear la sintonía principal de la serie antes de que su plataforma se deshaga por los residuos del lago de Springfield.',87,'Dan Castellaneta, Julie Kavner, Nancy Cartwright','Español',165,'https://www.youtube.com/watch?v=P8Ka6e82H9A&ab_channel=SantiagoGallardoBerm%C3%BAdez',no).
pelicula(60,'Bad Boys For Life', comedia, 2020,'Los detectives Mike Lowrey (Will Smith) y Marcus Burnett (Martin Lawrence) vuelven a hacer de las suyas.',124,'Will Smith, Martin Lawrence, Vanessa Hudgens','Español',145,'https://www.youtube.com/watch?v=bbqWBZEjSO8&ab_channel=SonyPicturesEspa%C3%B1a',no).

%ciencia_ficcion
pelicula(61,'Guardianes de la Galaxia: Voumen 3', ciencia_ficcion,2023,'Puede que Thanos (Josh Brolin), así como el padre de Peter Quill (Chris Pratt), Ego (Kurt Russel), sean ya historia, pero el daño que han dejado tras de sí aún se palpa en el seno de los Guardianes de la Galazia.',150, 'Chris Pratt, Zoe Saldana, Dave Bautista','Español',125,'https://www.youtube.com/watch?v=nFYA2kdHy0s&ab_channel=SensaCineTRAILERS',si).
pelicula(62,'Godzilla vs Kong', ciencia_ficcion, 2021,'Con el mundo todavía sacudido por la batalla entre Ghidorah y Godzilla, la humanidad ha comenzado a intentar coexistir con los Titanes.',114,'Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall','Español',145,'https://www.youtube.com/watch?v=WFmgnu1RjBc&ab_channel=YouTubeMovies',no).
pelicula(63,'Iron Man', ciencia_ficcion, 2008,'Tony Stark (Robert Downey Jr., Chaplin), dueño de Industrias Stark, inventor consagrado, vendedor de armas y playboy multimillonario, es secuestrado en Afganistán después de una demostración armamentística para el Ejército de los Estados Unidos.',126,'Robert Downey Jr., Terrence Howard, Gwyneth Paltrow','Español',165,'https://www.youtube.com/watch?v=8ugaeA-nMTc&ab_channel=RottenTomatoesClassicTrailers',no).
pelicula(64,'Los Juegos del Hambre', ciencia_ficcion, 2012, 'En su primera entrega, Los juegos del hambre, nos muestra un mundo distópico donde los Estados Unidos han sido devastados tras varias guerras, convirtiéndose en una nueva nación llamada Panem, un estado donde reina la pobreza.' ,142,'Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth','Español',135,'https://www.youtube.com/watch?v=TP46qVimUGM&ab_channel=YouTubeMovies',no).
pelicula(65,'Geminis', ciencia_ficcion, 2019,'Henry Brogan (Will Smith) ha sido toda su vida un asesino a sueldo del gobierno estadounidense.',117,'Will Smith, Mary Elizabeth Winstead, Clive Owen','Español',135,'https://www.youtube.com/watch?v=-S1foqWbNNk&ab_channel=YouTubeMovies',no).
pelicula(66,'Lucy', ciencia_ficcion, 2014,'Lucy (Scarlett Johanson, Don Jon) es una joven que ejerce de "mula", se dedica a ocultar droga en su cuerpo para narcotraficantes.',90,'Scarlett Johansson, Morgan Freeman, Min-sik Choi','Español',185,'https://www.youtube.com/watch?v=k3BdeoAK5N4&ab_channel=YouTubeMovies',no).
pelicula(67,'Splice Experimento Mortal', ciencia_ficcion, 2010,'Clive y Elsa son dos brillantes científicos: han conseguido combinar ADN de diferentes especies animales para conseguir fantásticos híbridos.',107,'Sarah Polley, Adrien Brody, Delphine Chanéac','Español',175,'https://www.youtube.com/watch?v=hvz5z-uEJIA&ab_channel=TERRORLAND',no).
pelicula(68,'Eternals', ciencia_ficcion, 2021, 'Esta película basada en los cómics de Marvel nos sitúa en medio de una guerra entre los Celestiales y los Desviantes.',157,'Gemma Chan, Richard Madden, Salma Hayek','Español',195,'https://www.youtube.com/watch?v=v1EkoQV4g5c&ab_channel=MarvelLatinoam%C3%A9ricaOficial',no).
pelicula(69,'Transformers', ciencia_ficcion, 2007,'Durante los primeros años del S. XXI, el conflicto alcanza la Tierra y el joven Sam Witwicky (Shia LaBeouf, Wall Street: El dinero nunca duerme) quien compra un coche sin saber que el vehículo tiene vida propia.',144,'Shia LaBeouf, Megan Fox, Josh Duhamel','Español',155,'https://www.youtube.com/watch?v=oQxrEhkv_cU&ab_channel=YouTubeMovies',no).
pelicula(70,'Soy Leyenda', ciencia_ficcion, 2007,'Un científico militar llamado Robert Neville, interpretado por Will Smith, es el único hombre con vida tras la inevitable expansión de un terrorífico virus.',100,'Will Smith, Alice Braga, Charlie Tahan','Español',195,'https://www.youtube.com/watch?v=hvz5z-uEJIA&ab_channel=TERRORLAND',no).

%animacion
pelicula(71,'Super Mario Bros', animacion, 2023,'Adaptación de la serie de videojuegos de Nintendo. La película cuenta la historia de Mario y Luigi, dos hermanos que viajan a un mundo oculto para rescatar a la Princesa Peach, capturada por el malvado Rey Bowser.',92,'Chris Pratt, Jack Black, Anya Taylor-Joy','Español',185,'https://www.youtube.com/watch?v=3iIjli_lx-g&ab_channel=YouTubeMovies',si).
pelicula(72,'El Gato con Botas', animacion,2023,'El Gato con Botas del universo Shrek regresa a las andadas.',102,'Antonio Banderas, Salma Hayek, Harvey Guillen','Español',150,'https://www.youtube.com/watch?v=kizMi_xe_Gc&ab_channel=THEFULLMOVIEVIDEOGAMETV',si).
pelicula(73,'Your Name', animacion, 2017,'La joven Mitsuha vive en un pequeño pueblecito entre las montañas. Sin muchas sorpresas ni demasiadas emociones, la adolescente tiene un par de amigos, además de a su hermana pequeña, su abuela y su padre, con el que tiene una relación algo distante.', 110,' Ryûnosuke Kamiki, Mone Kamishiraishi, Masami Nagasawa','Español',135,'https://www.youtube.com/watch?v=N0nvoAv5q8M&ab_channel=Alec',no).
pelicula(74,'El Rey Leon', animacion, 1994, 'Tras la muerte de su padre, encontrará por el camino una serie de compañeros de viaje que le enseñarán el verdadero significado de todas estas cosas.',90,'Matthew Broderick, Jonathan Taylor, James Earl Jones','Español',145,'https://www.youtube.com/watch?v=h-As2lUk6IA&ab_channel=Tr%C3%A1ilersconDoblajeEspa%C3%B1olLatinobySoldierBoy',no).
pelicula(75,'El mundo De Coraline', animacion, 2009,'Coraline acaba descubriendo en su casa una puerta secreta que, al ser cruzada, transporta a las personas a un mundo paralelo semejante a sus vidas pero mucho más divertido.',100,'Dakota Fanning, Teri Hatcher, Jennifer Saunders','Español',145,'https://www.youtube.com/watch?v=mabyooMwWmg&ab_channel=YouTubeMovies',no).
pelicula(76,'Shrek', animacion, 2001,'Shrek, un ogro verde, cínico, malicioso y con mal humor permanente, vive en una ciénaga que parece ser un remanso de paz.',90,' Mike Myers, Eddie Murphy, Cameron Diaz','Español',185,'https://www.youtube.com/watch?v=CwXOrWvPBPk&ab_channel=RottenTomatoesClassicTrailers',no).
pelicula(77,'Red', animacion, 2022,'Este largometraje gira en torno a Mei Lee, una joven de trece años que se debate constantemente entre ser obediente y el caos de la adolescencia.',100,' Rosalie Chiang, Sandra Oh, Maitreyi Ramakrishnan','Español',148,'https://www.youtube.com/watch?v=5IdjR-8MNSE&ab_channel=TrailersInSpanish',no).
pelicula(78,'Kung Fu Panda', animacion, 2008,'Po es un humilde oso panda que trabaja como camarero en un restaurante de fideos. Sin embargo, su verdadero sueño es otro, lo que realmente quiere es aprender kung-fu, pero su estado de forma no se lo permite',90,'Jack Black, Dustin Hoffman, Angelina Jolie','Español',175,'https://www.youtube.com/watch?v=kN1CRSZx-QA&list=PLvWoED0ul9pp__F0lurS3xKl2Wg2zsWuj&ab_channel=Josepmaniaco',no).
pelicula(79,'El Viaje de Chihiro', animacion, 2002,'Chihiro es una niña de diez años que está mudándose con sus padres a un nuevo hogar.' ,125,'Rumi Hiiragi, Miyu Irino, Mari Natsuki','Español',145,'https://www.youtube.com/watch?v=5Fgq4Osh6XQ&ab_channel=V%C3%A9rtigoFilms',no).
pelicula(80,'El Castillo Ambulante', animacion, 2006,'Una hacendosa joven llamada Sophie, trabaja sin descanso en la tienda de sombreros de su familia. Un día se topa con Howl un misteriosos y atractivo mago que esconde algo.' ,120,'Chieko Baishô, Takuya Kimura, Akihiro Miwa','Español',165,'https://www.youtube.com/watch?v=kjV5-_Z_Uys&ab_channel=V%C3%A9rtigoFilms',no).

todas_las_peliculas :-
    pelicula(ID, Titulo, Categoria, Anio, Sinopsis, Duracion, Actores, Idioma, Costo, Enlaces, Estreno),
    format('ID: ~w~n', [ID]),
    format('Título: ~w~n', [Titulo]),
    format('Categoría: ~w~n', [Categoria]),
    format('Año: ~w~n', [Anio]),
    format('Sinopsis: ~w~n', [Sinopsis]),
    format('Duración: ~w minutos~n', [Duracion]),
    format('Actores: ~w~n', [Actores]),
    format('Idioma: ~w~n', [Idioma]),
    format('Costo: ~w~n', [Costo]),
    format('Enlaces: ~w~n', [Enlaces]),
    format('Estreno: ~w~n', [Estreno]),
    nl,
    fail.

peliculas_por_categoria(Categoria) :-
    pelicula(ID, Titulo, Categoria, Anio, Sinopsis, Duracion, Actores, Idioma, Costo, Enlaces, Estreno),
    format('ID: ~w~n', [ID]),
    format('Título: ~w~n', [Titulo]),
    format('Categoría: ~w~n', [Categoria]),
    format('Año: ~w~n', [Anio]),
    format('Sinopsis: ~w~n', [Sinopsis]),
    format('Duración: ~w minutos~n', [Duracion]),
    format('Actores: ~w~n', [Actores]),
    format('Idioma: ~w~n', [Idioma]),
    format('Costo: ~w~n', [Costo]),
    format('Enlaces: ~w~n', [Enlaces]),
    format('Estreno: ~w~n', [Estreno]),
    nl,
    fail.

estrenos(Estreno) :-
    pelicula(ID, Titulo, Categoria, Anio, Sinopsis, Duracion, Actores, Idioma, Costo, Enlaces, Estreno),
    format('ID: ~w~n', [ID]),
    format('Título: ~w~n', [Titulo]),
    format('Categoría: ~w~n', [Categoria]),
    format('Año: ~w~n', [Anio]),
    format('Sinopsis: ~w~n', [Sinopsis]),
    format('Duración: ~w minutos~n', [Duracion]),
    format('Actores: ~w~n', [Actores]),
    format('Idioma: ~w~n', [Idioma]),
    format('Costo: ~w~n', [Costo]),
    format('Enlaces: ~w~n', [Enlaces]),
    format('Estreno: ~w~n', [Estreno]),
    nl,
    fail.

